<a href="https://colab.research.google.com/github/ddori/Tensorflow_tutorial/blob/master/tensorflow_constant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
points = [[1,2,3],[4,5,6]]
print(points)

[[1, 2, 3], [4, 5, 6]]


In [0]:
vectors = tf.constant(points)
print(vectors)

#shape를 확인 하는 방법은 두가지가 있습니다.
print(vectors.get_shape())
print(vectors.shape)

Tensor("Const_6:0", shape=(2, 3), dtype=int32)
(2, 3)
(2, 3)


In [0]:
#2D tensor를 3D로 확장
#tf.expand_dims의 2번째 파라미터는 차원을 추가할 인덱스를 적는 란, 0을 넣어보겠습니다.
#뒤에 있는 tf.Session.run 과 t.eval은 같은 의미.

expanded_vectors = tf.expand_dims(vectors,0).eval(session=sess)
print(expanded_vectors)

#shape를 확인 하는 방법은 두가지가 있습니다.
#print(expanded_vectors.get_shape())
print(expanded_vectors.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [0]:
#2D tensor를 3D로 확장
#tf.expand_dims의 2번째 파라미터는 차원을 추가할 인덱스를 적는 란, 1을 넣어보겠습니다
#뒤에 있는 tf.Session.run 과 t.eval은 같은 의미.
expanded_vectors = tf.expand_dims(vectors,1).eval(session=sess)
print(expanded_vectors)

#shape를 확인 하는 방법은 두가지가 있습니다.
#print(expanded_vectors.get_shape())
print(expanded_vectors.shape)

[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


상수 여러가지 방법으로 생성

In [0]:
#첫번째 파라미터로 들어간 형식을 그대로 따라하는데, value가 0으로 바뀜 
#밑은 1x3 tensor가 만들어짐
zeros = tf.zeros_like([4,3,3], dtype=tf.int32, name='zeros')
print(sess.run(zeros))

[0 0 0]


In [0]:
#제일 많이 쓰이는 방법 3x4x5 tensor가 만들어짐
zeros2 = tf.zeros([3,4,5], dtype =tf.int32, name = 'zeros2')
print(sess.run(zeros2))

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [0]:
#zeros와 비슷, 하지만 1로 초기화 하는 방식
ones = tf.ones([2,2,3], dtype = tf.float32, name = 'ones1')
print(sess.run(ones))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [0]:
#2x3 tensor를 만들지만, 두번째 파라미터 값으로 채워 넣음. 
fill = tf.fill([2,3] , 9)
print(sess.run(fill))

[[9 9 9]
 [9 9 9]]


In [0]:
#zeros_like와 매우 흡사, 하지만 constant로 설정하면 value도 함께 생성
contant = tf.constant([2,3,4])
print(sess.run(contant))

[2 3 4]


In [0]:
#tf.fill([2,3],-1.0)과 같다.
tensor = tf.constant(-1.0, shape=[2, 3])
print(sess.run(tensor))

[[-1. -1. -1.]
 [-1. -1. -1.]]


난수 상수 생성

In [0]:
#정규분포
#mean은 평균이고, stddev 는 표준편차(Standard Deviation)
norm = tf.random_normal([2,3], mean = -1, stddev = 4)
print(sess.run(norm))

[[-1.3577713 -9.036874  -6.167119 ]
 [-1.5161736  0.3975426  2.2483747]]


In [0]:
#주어진 값을 shuffle
#제일 바깥에 있는 차원을 기준으로 shuffle
c = tf.constant([[1,2],[3,4],[5,6]])
shuff = tf.random_shuffle(c)
print(sess.run(shuff))

[[1 2]
 [5 6]
 [3 4]]


In [0]:
#균등분포 난수
unif = tf.random_uniform([2,3], minval=0, maxval=3)
print(sess.run(unif))

[[0.8728223  2.5516238  1.0395688 ]
 [1.6830196  0.00823796 2.4787753 ]]


시퀸스 상수 생성(그대로 연속적인 상수를 생성하는 방법)

In [0]:
#첫번째 parameter 부터 2번째 parameter 까지, 세번째 parameter는 생성하는 갯수, 따라서 element의 간격은 (2_parameter - 1_parameter)/(3_parameter-1)
lin = tf.linspace(10.0, 12.0, 5, name = 'linspace')
print(sess.run(lin))

[10.  10.5 11.  11.5 12. ]


In [0]:
#start부터 시작하여 limit 까지 delta의 증가량 만큼 확장하여 정수 리스트 생성( limit은 포함 x)
ran = tf.range(start=3, limit=7, delta=2)
print(sess.run(ran))

[3 5]


In [0]:
#start의 default는 0
ran2 = tf.range(8)
print(sess.run(ran2))

[0 1 2 3 4 5 6 7]


난수 생성시 Seed의 활용

In [0]:
#seed를 주고 random한 값을 생성하면 매 session마다 값이 같음

#ramdom_uniform 과 ramdom_normal의 차이는
#reference : https://www.tensorflow.org/api_docs/python/tf/random/normal
'''
#random_normal
tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
Outputs random values from a normal distribution.

#random_uniform
tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
Outputs random values from a uniform distribution.
'''

#random_normal은 평균과 표준편차를 기준으로 random value를 생성한다는 점
#random_uniform은 최소값과 default 값인 최대값을 세팅하고 안에서 random value를 생성한다는 점이다.
a = tf.random_uniform([1], seed=1)
b = tf.random_normal([1])

print('Session1')
with tf.Session() as sess1:
  print(sess1.run(a))
  print(sess1.run(a))
  print(sess1.run(b))
  print(sess1.run(b))
  

Session1
[0.77498245]
[0.39846957]
[-0.08693722]
[0.04120286]


In [0]:
print('Session2')
with tf.Session() as sess2:
  print(sess2.run(a))
  print(sess2.run(a))
  print(sess2.run(b))
  print(sess2.run(b))

Session2
[0.2390374]
[0.22267115]
[0.2533507]
[-1.360431]


In [0]:
# tf.set_random_seed 통해 모든 random value generation function들이 매번 같은 값을 반환
tf.set_random_seed(12)
a = tf.random_uniform([1])
b = tf.random_normal([1])

In [0]:
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  
  print(sess1.run(a))  
  print(sess1.run(b))  
  print(sess1.run(b))  

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  
  print(sess2.run(a))  
  print(sess2.run(b)) 
  print(sess2.run(b)) 


Session 1
[0.34005928]
[0.9032984]
[-0.32772705]
[-0.61718315]
Session 2
[0.34005928]
[0.9032984]
[-0.32772705]
[-0.61718315]
